-- ============================================================
-- RÉINITIALISATION COMPLÈTE DE LA BASE
-- ============================================================

-- 1. Supprimer les données dans l'ordre des dépendances
DELETE FROM notifications;
DELETE FROM notification_types;
DELETE FROM demandes_modification_dossier;
DELETE FROM documents;
DELETE FROM evenements_instances;
DELETE FROM evenements;
DELETE FROM budgets;
DELETE FROM previsions_depenses;
DELETE FROM depenses;
DELETE FROM echeances_contrats;
DELETE FROM contrats_charges;
DELETE FROM fournisseurs;
DELETE FROM categories_depenses;
DELETE FROM paiements;
DELETE FROM echeances;
DELETE FROM echeanciers;
DELETE FROM grilles_tarifaires;
DELETE FROM moyennes;
DELETE FROM notes;
DELETE FROM absences;
DELETE FROM seances;
DELETE FROM modifications_edt;
DELETE FROM emploi_du_temps;
DELETE FROM affectations_enseignement;
DELETE FROM inscriptions;
DELETE FROM etudiants_parents;
DELETE FROM profils_parents;
DELETE FROM profils_comptables;
DELETE FROM profils_secretariat;
DELETE FROM profils_directeurs;
DELETE FROM profils_professeurs;
DELETE FROM profils_etudiants;
DELETE FROM user_roles;
DELETE FROM users;
DELETE FROM periodes;
DELETE FROM coefficients;
DELETE FROM matieres;
DELETE FROM salles;
DELETE FROM classes;
DELETE FROM niveaux;
DELETE FROM annees_scolaires;
DELETE FROM etablissements;
DELETE FROM roles;
DELETE FROM horaire_edt;
DELETE FROM permissions;
DELETE FROM role_permissions;

-- 2. Réinitialiser les séquences (index à 1)
ALTER SEQUENCE etablissements_id_seq RESTART WITH 1;
ALTER SEQUENCE annees_scolaires_id_seq RESTART WITH 1;
ALTER SEQUENCE niveaux_id_seq RESTART WITH 1;
ALTER SEQUENCE classes_id_seq RESTART WITH 1;
ALTER SEQUENCE salles_id_seq RESTART WITH 1;
ALTER SEQUENCE matieres_id_seq RESTART WITH 1;
ALTER SEQUENCE coefficients_id_seq RESTART WITH 1;
ALTER SEQUENCE periodes_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;
ALTER SEQUENCE profils_etudiants_id_seq RESTART WITH 1;
ALTER SEQUENCE profils_professeurs_id_seq RESTART WITH 1;
ALTER SEQUENCE profils_directeurs_id_seq RESTART WITH 1;
ALTER SEQUENCE profils_secretariat_id_seq RESTART WITH 1;
ALTER SEQUENCE profils_comptables_id_seq RESTART WITH 1;
ALTER SEQUENCE profils_parents_id_seq RESTART WITH 1;
ALTER SEQUENCE inscriptions_id_seq RESTART WITH 1;
ALTER SEQUENCE affectations_enseignement_id_seq RESTART WITH 1;
ALTER SEQUENCE emploi_du_temps_id_seq RESTART WITH 1;
ALTER SEQUENCE modifications_edt_id_seq RESTART WITH 1;
ALTER SEQUENCE seances_id_seq RESTART WITH 1;
ALTER SEQUENCE absences_id_seq RESTART WITH 1;
ALTER SEQUENCE notes_id_seq RESTART WITH 1;
ALTER SEQUENCE moyennes_id_seq RESTART WITH 1;
ALTER SEQUENCE grilles_tarifaires_id_seq RESTART WITH 1;
ALTER SEQUENCE echeanciers_id_seq RESTART WITH 1;
ALTER SEQUENCE echeances_id_seq RESTART WITH 1;
ALTER SEQUENCE paiements_id_seq RESTART WITH 1;
ALTER SEQUENCE categories_depenses_id_seq RESTART WITH 1;
ALTER SEQUENCE fournisseurs_id_seq RESTART WITH 1;
ALTER SEQUENCE contrats_charges_id_seq RESTART WITH 1;
ALTER SEQUENCE echeances_contrats_id_seq RESTART WITH 1;
ALTER SEQUENCE previsions_depenses_id_seq RESTART WITH 1;
ALTER SEQUENCE depenses_id_seq RESTART WITH 1;
ALTER SEQUENCE budgets_id_seq RESTART WITH 1;
ALTER SEQUENCE evenements_id_seq RESTART WITH 1;
ALTER SEQUENCE evenements_instances_id_seq RESTART WITH 1;
ALTER SEQUENCE notification_types_id_seq RESTART WITH 1;
ALTER SEQUENCE notifications_id_seq RESTART WITH 1;
ALTER SEQUENCE documents_id_seq RESTART WITH 1;
ALTER SEQUENCE demandes_modification_dossier_id_seq RESTART WITH 1;
ALTER SEQUENCE audit_log_id_seq RESTART WITH 1;
ALTER SEQUENCE roles_id_seq RESTART WITH 1;
ALTER SEQUENCE permissions_id_seq RESTART WITH 1;
ALTER SEQUENCE role_permissions_id_seq RESTART WITH 1;
ALTER SEQUENCE horaire_edt_id_seq RESTART WITH 1;
